CFLAGS	+= -I. -g -O0
CFLAGS	+= -Wall -Wpointer-arith
CFLAGS	+= -Wstrict-prototypes -Wmissing-prototypes
CFLAGS	+= -Wmissing-declarations -Wshadow
CFLAGS	+= -Wpointer-arith -Wcast-qual
CFLAGS	+= -Wsign-compare

PROG	= client

SRCS	= client.c

.include <bsd.prog.mk>
